### ISSUE TITLE
Styling/format issue checklist

### ISSUE THREAD

**Issue by NJscc** [NJscc/stardew_forum#64]
-  [x]  Task across all pages - add 'border-radius' and border properties to CSS to round corners and make elements stand out more on the page.
- Main
- [x] Color palette change - use stardew valley palette listed in slack (purple header with dark yellow text, among other issues)
- Home
- [x] spacing of 'recent' and 'category' headers
- [x] display recent posts
- [x] display linked categories
- [x] revise header buttons
- Login
- [x] arrange blocks left to right on large screen
- [x] style buttons
- Posts
- [x] display posts, topics
- [x] style buttons
- Profile
- [x] display recent posts from user
- [x] make sure profile buttons only appear for logged-in user
- [x] style buttons
- [x] spacing issues for right block between header and footer
- Submit_post
- [x] style buttons and text
- [x] link categories
- Submit_profile
- [x] display posts
- [x] right block placement
- [x] left block styling 
- [x] check as group - keep 'welcome' test block?
- Submit_topic
- [x] link categories
- [x] right block placement/spacing issues with neighboring elements
- [x] right block text styling
- Topic
- [ ] display topics, usernames
- [x] link categories
- [x] refine placement and spacing around both the right and left blocks
